version: "3.9"

services:
  vendure:
    build:
      context: .
      dockerfile: docker/vendure/Dockerfile
    container_name: ahizan_backend
    restart: unless-stopped
    ports:
      - "3000" # Expose interne pour le réseau, pas public
    env_file: .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - STOREFRONT_URL=https://ahizan.com
      - ASSET_URL_PREFIX=https://media.ahizan.com
      # Autres variables Vendure
    labels:
      - "VIRTUAL_HOST=api.ahizan.com,administrator.ahizan.com"
      - "VIRTUAL_PORT=3000"
    networks:
      - web
      - internal

  storefront:
    build:
      context: .
      dockerfile: docker/storefront/Dockerfile
    container_name: ahizan_storefront
    restart: unless-stopped
    ports:
      - "3000"
    env_file: .env
    environment:
      - VENDURE_SHOP_API_URL=http://ahizan_backend:3000/shop-api
      - NEXT_PUBLIC_VENDURE_SHOP_API_URL=https://api.ahizan.com/shop-api
    labels:
      - "VIRTUAL_HOST=ahizan.com,www.ahizan.com"
      - "VIRTUAL_PORT=3000"
    networks:
      - web
      - internal

  seller:
    build:
      context: .
      dockerfile: docker/seller/Dockerfile
    container_name: ahizan_seller
    restart: unless-stopped
    ports:
      - "3000"
    env_file: .env
    environment:
      - VENDURE_SHOP_API_URL=http://ahizan_backend:3000/shop-api
      - NEXT_PUBLIC_VENDURE_SHOP_API_URL=https://api.ahizan.com/shop-api
    labels:
      - "VIRTUAL_HOST=seller.ahizan.com"
      - "VIRTUAL_PORT=3000"
    networks:
      - web
      - internal

  media:
    build: ./docker/media
    container_name: ahizan_media
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - ./backend/static/assets:/srv/ahizan/storage
    depends_on:
      - db
    labels:
      - "VIRTUAL_HOST=media.ahizan.com"
      - "VIRTUAL_PORT=80"
    networks:
      - web

  db:
    image: postgres:16-alpine
    container_name: ahizan_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal
    # Pas de port mapping nécessaire, communication interne Docker uniquement

volumes:
  db_data:

networks:
  web:
    external: true
  internal:
    driver: bridge
